export const ERRORS = {
  STORE_USER: {
    EMAIL_ALREADY_REGISTER: 'STORE_USER_EMAIL_ALREADY_REGISTER',
    NOT_FOUND: 'STORE_USER_NOT_FOUND',
  },
  AUTH: {
    INCORRECT_EMAIL_OR_PASSWORD: 'AUTH_INCORRECT_EMAIL_OR_PASSWORD',
    PROVIDE_TOKEN: 'AUTH_PROVIDE_TOKEN'
  },
  STORE: {
    PROVIDED_OWNER_ID_ALREADY_HAVE_STORE: 'STORE-PROVIDED_OWNER_ID_ALREADY_HAVE_STORE',
    NOT_FOUND: 'STORE_NOT_FOUND'
  },
  MENU_GROUP: {
    NOT_FOUND: 'MENU_GROUP_NOT_FOUND'
  },
  MENU: {
    NOT_FOUND: 'MENU_NOT_FOUND'
  },
  PRODUCT: {
    NOT_FOUND: 'PRODUCT_NOT_FOUND'
  },
  FILE_UPLOAD: {
    REQUIRED: 'FILE_UPLOAD_FIELD_FILE_IS_REQUIRED'
  },
  EMAIL_VERIFICATION_TOKEN: {
    WAITING_UNTIL_YOU_CAN_RESEND: 'EMAIL_VERIFICATION_TOKEN_WAITING_UNTIL_YOU_CAN_RESEND',
    LIMIT_MAX_ATTEMPTS_REACHED  : 'EMAIL_VERIFICATION_TOKEN_LIMIT_MAX_ATTEMPTS_REACHED',
    EXPIRED: 'EMAIL_VERIFICATION_EXPIRED',
    NOT_FOUND: 'EMAIL_VERIFICATION_NOT_FOUND',
    ACCOUNT_ALREADY_VERIFIED: 'EMAIL_VERIFICATION_ACCOUNT_ALREADY_VERIFIED',
  }
}