export const ERRORS = {
  STORE_USER: {
    EMAIL_ALREADY_REGISTER: 'STORE_USER_EMAIL_ALREADY_REGISTER'
  },
  AUTH: {
    INCORRECT_EMAIL_OR_PASSWORD: 'AUTH_INCORRECT_EMAIL_OR_PASSWORD',
    PROVIDE_TOKEN: 'AUTH_PROVIDE_TOKEN'
  }
}